// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJS2d--uWey6N9CMsC6fqkOauh-7OFZEQ',
    appId: '1:1092044780006:web:419a0274c55697f201e627',
    messagingSenderId: '1092044780006',
    projectId: 'fir-rocks-music-task',
    authDomain: 'fir-rocks-music-task.firebaseapp.com',
    storageBucket: 'fir-rocks-music-task.firebasestorage.app',
    measurementId: 'G-9J2457JGCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoe1lxuFHv0BPXSCc_6D1r7IkmlvWcq8E',
    appId: '1:1092044780006:android:cf043b63467dadbc01e627',
    messagingSenderId: '1092044780006',
    projectId: 'fir-rocks-music-task',
    storageBucket: 'fir-rocks-music-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFMg09JudJ5623mvvvyyeaM_Arw0CLZ6Q',
    appId: '1:1092044780006:ios:0b1ddaee37d022e001e627',
    messagingSenderId: '1092044780006',
    projectId: 'fir-rocks-music-task',
    storageBucket: 'fir-rocks-music-task.firebasestorage.app',
    iosBundleId: 'com.example.sRocksMusicTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFMg09JudJ5623mvvvyyeaM_Arw0CLZ6Q',
    appId: '1:1092044780006:ios:0b1ddaee37d022e001e627',
    messagingSenderId: '1092044780006',
    projectId: 'fir-rocks-music-task',
    storageBucket: 'fir-rocks-music-task.firebasestorage.app',
    iosBundleId: 'com.example.sRocksMusicTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJS2d--uWey6N9CMsC6fqkOauh-7OFZEQ',
    appId: '1:1092044780006:web:c1e4e61a18d0001a01e627',
    messagingSenderId: '1092044780006',
    projectId: 'fir-rocks-music-task',
    authDomain: 'fir-rocks-music-task.firebaseapp.com',
    storageBucket: 'fir-rocks-music-task.firebasestorage.app',
    measurementId: 'G-HM12ZH87F7',
  );
}
